services:
  # Backend API Service
  - type: web
    name: luxury-ecommerce-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://luxury-ecommerce-frontend.onrender.com
      - key: DB_HOST
        value: dpg-d3d6k9q4d50c73d4ek1g-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: luxury_ecommerce_db_e7z8
      - key: DB_USER
        value: luxury_ecommerce_db_e7z8_user
      - key: DB_PASSWORD
        value: wwZwzCLXOL1sg4l3bCCQsn2gW1nBZXJW
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://luxury-ecommerce-frontend.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: duywipohs
      - key: CLOUDINARY_API_KEY
        value: 381183831597114
      - key: CLOUDINARY_API_SECRET
        value: aZowyFfya7-P_uIIrK5dx8c0nbo
      - key: CLOUDINARY_SECURE
        value: "true"
      - key: CLOUDINARY_AUTO_OPTIMIZE
        value: "true"

  # Frontend Static Site
  - type: web
    name: luxury-ecommerce-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    plan: free
    region: singapore
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://luxury-ecommerce-api.onrender.com
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false